version: '3'

#a service is essentially a container. each container you want to start-up define as a different service.
services:
  api:
    build : .
    ports: 
      - 8000:8000
    env_file:
      - ./.env
