version: '3'

#a service is essentially a container. each container you want to start-up define as a different service.
services:
  api:
    build: .
    depends_on:
      - db
    ports: 
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=fastapi
      - DB_USERNAME=postgres
      - DB_PASSWORD=password123
      - SECRET_KEY=c913b8fae0e79d0b72838ee648071b7572a3a91409c4e2254960fa12b8ce27b6
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES= 60
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --reload'
    volumes:
      - ./:/code:ro #read only

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi

volumes:
  postgres_data:
